export const colorItem = {
    mainColor: '#fff',
    subMainColor: '#00308E',
    mainLightColor: "#c0efe7",
    subMainLightColor: "#e0f9fd",
    appColor: "#e0f9fd",
    textColor: "#000",
    white: "#fff",
    orange: "#ff725e",
    black: "#000",
    light_grey: "#828693",
    subDarkGrey:"#ababab",
    lightGreyText: '#373737',
    brightBlue: "#0A7CFF",
    inActiveColor: "#eee",
    green: "#4cb050",
    red: "#ab0213",
    SelectionColor: '#afffca',
    darkGrey: "#44485d",
    lightPink: "#edd3e0",
    darkPink: "#F99CBB",
    darkGreen:'#003418',
    teamSelect:"#fee2cc",
    OrangeHeading:"#ef9e32"
} 